### ISSUE TITLE
[Tool Parts] Enchanting-related crash

### ISSUE THREAD

**Issue by Eldog02** [brotazoa/Alloygery#15] opened 2022-03-24 06:22 UTC
I enchanted a Titanium Gold pickaxe while testing, then tried to stack more enchants on with an anvil. Upon putting the enchanted book into the anvil with the pickaxe (or vice versa), the game immediately crashed back to the launcher.

![image](https://user-images.githubusercontent.com/34759177/159854726-ce942ed8-8b11-4756-8f14-2882857e46f0.png)
![2022-03-24_01 20 01](https://user-images.githubusercontent.com/34759177/159854590-fec348af-9450-448e-b9e8-fb666772ac67.png)
[crash-2022-03-24_01.14.57-client.txt](https://github.com/brotazoa/Alloygery/files/8338890/crash-2022-03-24_01.14.57-client.txt)

**Comment by brotazoa** [comment] 2022-03-24 14:20
Thanks for the crash log, I think I know where the issue is.

**Comment by brotazoa** [comment] 2022-03-25 22:26
I am going to close this, as alpha+6 fixes this issue. If the crash persists, you are welcome to reopen this issue.

**Closed as completed by brotazoa** 2022-03-25 22:26 UTC
