### ISSUE TITLE
[1.18.1] Appears to break REI recipe lookup

### ISSUE THREAD

**Issue by kwpugh** [brotazoa/Alloygery#3] opened 2022-01-28 17:56 UTC
Nice work on the mod!!

Trying it out I noticed with your mod in the mix the REI "u" and "r" don't appear to work for recipe lookup.   After disabling the mod and NBTCrafting, REI works fine.

Keep up the good work.

**Comment by brotazoa** [comment] 2022-01-29 02:40
In my testing I was not able to reproduce this issue, but the last release made some significant changes that might fix the problem. Let me know if the issue persists so I can keep looking into it, or close this issue.

**Comment by brotazoa** [comment] 2022-01-29 02:41
Also, thank you so much for all the positive encouragement. Means a lot.

**Comment by kwpugh** [comment] 2022-01-29 02:42
Thanks for looking into it.  Im testing it now.

**Comment by kwpugh** [comment] 2022-01-29 02:44
I remember when I started making mods, nice to get some recognition for hard work.

**Comment by brotazoa** [comment] 2022-01-30 17:35
This issue seems to be resolved, so I am going to close this. Please reopen this issue if the problem persists.

**Closed as completed by brotazoa** 2022-01-30 17:35 UTC
